name: validate-PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      - name: Setup Node.js 20     
      - uses: actions/setup-node@v3

      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'

      ## for local act testing
      # - run: npm install -g yarn

      - run: yarn install

      - name: Validate PR
        run: yarn validate-PR
